# FluentBuilders.Text - Dependabot Configuration
# Automated dependency updates for security and maintenance
# Based on CODE_RULES.md dependency management standards

version: 2

updates:
  # .NET NuGet packages
  - package-ecosystem: "nuget"
    directory: "/csharp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Stockholm"

    # Security updates get higher priority
    open-pull-requests-limit: 10

    # Commit message preferences
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

    # Reviewers (customize as needed)
    reviewers:
      - "MarcusMedina"

    # Auto-merge security patches
    allow:
      - dependency-type: "all"

    # Ignore specific versions
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

    # Group updates for better PR management
    groups:
      test-dependencies:
        patterns:
          - "xunit*"
          - "FluentAssertions"
          - "coverlet*"
          - "Microsoft.NET.Test.Sdk"

      analyzers:
        patterns:
          - "Microsoft.CodeAnalysis.*"
          - "StyleCop.Analyzers"
          - "SonarAnalyzer.CSharp"

      microsoft-packages:
        patterns:
          - "Microsoft.*"
          - "System.*"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Stockholm"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "ci"
      include: "scope"

    reviewers:
      - "MarcusMedina"

  # Node.js dependencies (future)
  - package-ecosystem: "npm"
    directory: "/node"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Stockholm"

    open-pull-requests-limit: 5

    versioning-strategy: increase

    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Python dependencies (future)
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Europe/Stockholm"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"

# Security best practices:
# 1. Enable Dependabot security updates in repository settings
# 2. Configure branch protection rules to require reviews
# 3. Enable automated security alerts
# 4. Review and merge security updates promptly
