name: CI/CD - C#

on:
  push:
    branches: [ main ]
    paths:
      - 'csharp/**'
      - '.github/workflows/ci-csharp.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'csharp/**'
  release:
    types: [ published ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ./csharp
      run: dotnet restore

    - name: Build
      working-directory: ./csharp
      run: dotnet build --no-restore --configuration Release

    - name: Test
      working-directory: ./csharp
      run: dotnet test --no-build --configuration Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.opencover.xml
        fail_ci_if_error: false

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Pack
      working-directory: ./csharp
      run: dotnet pack --configuration Release

    - name: Push to NuGet
      working-directory: ./csharp
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
