name: CI/CD - Node.js

on:
  push:
    branches: [ main ]
    paths:
      - 'node/**'
      - '.github/workflows/ci-node.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'node/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20.x

    - name: Install dependencies
      working-directory: ./node
      run: npm ci

    - name: Build
      working-directory: ./node
      run: npm run build

    - name: Test
      working-directory: ./node
      run: npm test
